syntax = "proto3";

import "google/protobuf/timestamp.proto";
import "google/api/annotations.proto";

package order.v1;

option go_package = "ecommerce/gen/order/v1;orderv1";

enum OrderStatus {
  ORDER_STATUS_UNSPECIFIED = 0;
  ORDER_STATUS_PENDING = 1;
  ORDER_STATUS_CONFIRMED = 2;
  ORDER_STATUS_CANCELLED = 3;
}

message Order {
  string order_id = 1;
  string user_id = 2;
  repeated OrderItem items = 3;
  OrderStatus status = 4;
  google.protobuf.Timestamp created_at = 5;
}

message OrderItem {
  string product_id = 1;
  int32 quantity = 2;
  // TODO: int64 price_at_purchase = 3; + UpdateProductPrice. Заморозить цену при заказе
}

service OrderService {
  // TODO: think about gateway
  rpc CreateOrder(stream OrderItemRequest) returns (CreateOrderResponse);

  rpc GetOrder(GetOrderRequest) returns (GetOrderResponse) {
    option (google.api.http) = {
      get: "/v1/orders/{order_id}"
    };
  }

  rpc ListOrders(ListOrdersRequest) returns (ListOrdersResponse) {
    option (google.api.http) = {
      get: "/v1/orders"
    };
  }
}

message OrderItemRequest {
  string user_id = 1;   // TODO: oneof
  OrderItem item = 2;
}

message CreateOrderResponse {
  Order order = 1;
}

message GetOrderRequest {
  string order_id = 1;
}

message GetOrderResponse {
  Order order = 1;
}

message ListOrdersRequest {}

message ListOrdersResponse {
  repeated Order orders = 1;
}